### ISSUE TITLE
semicolon (;) in js file ??!!

### ISSUE THREAD

**Issue by leninhasda** [hasinhayder/fatalsafe#1]
@hasinhayder bhai, you have a semicolon in first line of js script, is it intentional or a mistake?! :confused: 
 if it is intentional, is there any specific reason (standard / good practice) for it?

+1 for this awesome plugin :smile:

**Comment by hasinhayder** [comment]
http://stackoverflow.com/questions/7145514/whats-the-purpose-of-starting-semi-colon-at-beginning-of-javascript :)

**Comment by leninhasda** [comment]
aahh... googled with wrong keyword(s) again. thanku for the tips :+1:
